### PR TITLE
Update our "registry" install to use the included Godeps libraries so that it doesn't require anything from our current source (hence moving it up for better caching too)

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by jfrazelle** [comment]
such title
long
wow

**Comment by tianon** [comment]
I almost went longer :smiling_imp:

**Comment by jlhawn** [comment]
more than 50 chars for a git commit title?

I'll allow it.

**Comment by tianon** [comment]
Just don't tell Linus. :angel:

**Pull request merged**
